version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: vagas
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: vagas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  pgdata:
